"""H3 Relay ComfyUI custom nodes."""

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

from .person_remover import NODE_CLASS_MAPPINGS as REMOVAL_NODES, NODE_DISPLAY_NAME_MAPPINGS as REMOVAL_NAMES

NODE_CLASS_MAPPINGS.update(REMOVAL_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(REMOVAL_NAMES)

from .windowed_edit import NODE_CLASS_MAPPINGS as EDIT_NODES, NODE_DISPLAY_NAME_MAPPINGS as EDIT_NAMES
NODE_CLASS_MAPPINGS.update(EDIT_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(EDIT_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
